In [4]:
pip install pyforest # imports all the required libraries for EDA

In [5]:
import pyforest
import warnings
warnings.filterwarnings('ignore')

In [6]:
df = pd.read_csv('/content/Bank_churn_modelling.csv')
df.head(2)

<IPython.core.display.Javascript object>

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0

[2 rows x 14 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [8]:
df.describe(include = 'all').T

count unique     top  ...          50%          75%          max
RowNumber        10000    NaN     NaN  ...       5000.5      7500.25        10000
CustomerId       10000    NaN     NaN  ...  1.56907e+07  1.57532e+07  1.58157e+07
Surname          10000   2932   Smith  ...          NaN          NaN          NaN
CreditScore      10000    NaN     NaN  ...          652          718          850
Geography        10000      3  France  ...          NaN          NaN          NaN
Gender           10000      2    Male  ...          NaN          NaN          NaN
Age              10000    NaN     NaN  ...           37           44           92
Tenure           10000    NaN     NaN  ...            5            7           10
Balance          10000    NaN     NaN  ...      97198.5       127644       250898
NumOfProducts    10000    NaN     NaN  ...            1            2            4
HasCrCard        10000    NaN     NaN  ...            1            1            1
IsActiveMember   10000    NaN     NaN  ...            1            1            1
EstimatedSalary  10000    NaN     NaN  ...       100194       149388       199992
Exited           10000    NaN     NaN  ...            0            0            1

[14 rows x 11 columns]

In [9]:
df=df.drop(['RowNumber', 'CustomerId', 'Surname'],axis=1)

In [10]:
'''cat=["Geography","Gender","HasCrCard","IsActiveMember","Exited"]
con=['CreditScore',"Tenure","Balance",'NumOfProducts',"EstimatedSalary","Age"]
for i in cat:
    sns.countplot(x=i,data=df)
    plt.show()'''

'cat=["Geography","Gender","HasCrCard","IsActiveMember","Exited"]\ncon=[\'CreditScore\',"Tenure","Balance",\'NumOfProducts\',"EstimatedSalary","Age"]\nfor i in cat:\n    sns.countplot(x=i,data=df)\n    plt.show()'

In [11]:
'''for i in con:
    sns.distplot(df[i])
    plt.show()'''

'for i in con:\n    sns.distplot(df[i])\n    plt.show()'

In [12]:
'''sns.countplot(x="Gender",hue="Exited",data=df)
plt.show()'''

'sns.countplot(x="Gender",hue="Exited",data=df)\nplt.show()'

In [13]:
'''sns.barplot(x="Geography",y="Exited",data=df)
plt.show()'''

'sns.barplot(x="Geography",y="Exited",data=df)\nplt.show()'

In [14]:
'''sns.distplot(df["CreditScore"][df["Exited"]==1],color='r')
sns.distplot(df["CreditScore"][df["Exited"]==0],color='g')
plt.show()'''

'sns.distplot(df["CreditScore"][df["Exited"]==1],color=\'r\')\nsns.distplot(df["CreditScore"][df["Exited"]==0],color=\'g\')\nplt.show()'

In [15]:
'''df.info()'''

'df.info()'

In [43]:
# logistic regression
#a = ['CreditScore','Geography','Gender','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary']
x = df.drop(['Exited'],axis = 1)
y = df[['Exited']]
print(x)
print(y)

      CreditScore  Geography  ...  IsActiveMember  EstimatedSalary
0             619          0  ...               1        101348.88
1             608          2  ...               1        112542.58
2             502          0  ...               0        113931.57
3             699          0  ...               0         93826.63
4             850          2  ...               1         79084.10
...           ...        ...  ...             ...              ...
9995          771          0  ...               0         96270.64
9996          516          0  ...               1        101699.77
9997          709          0  ...               1         42085.58
9998          772          1  ...               0         92888.52
9999          792          0  ...               0         38190.78

[10000 rows x 10 columns]
      Exited
0          1
1          0
2          1
3          0
4          0
...      ...
9995       0
9996       0
9997       1
9998       1
9999       0

[10000 rows 

In [44]:
x.shape

(10000, 10)

In [45]:
y.shape

(10000, 1)

In [46]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Geography']=encoder.fit_transform(df['Geography'])
df['Gender']= encoder.fit_transform(df['Gender'])
'''onehotencoder = OneHotEncoder()
x = onehotencoder.fit_transform(x).toarray()
x = x[:,1:]'''

'onehotencoder = OneHotEncoder()\nx = onehotencoder.fit_transform(x).toarray()\nx = x[:,1:]'

In [47]:
pip install sklearn

In [48]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,train_size=0.8,random_state=42)

<IPython.core.display.Javascript object>

In [49]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8000 entries, 9254 to 7270
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      8000 non-null   int64  
 1   Geography        8000 non-null   int64  
 2   Gender           8000 non-null   int64  
 3   Age              8000 non-null   int64  
 4   Tenure           8000 non-null   int64  
 5   Balance          8000 non-null   float64
 6   NumOfProducts    8000 non-null   int64  
 7   HasCrCard        8000 non-null   int64  
 8   IsActiveMember   8000 non-null   int64  
 9   EstimatedSalary  8000 non-null   float64
dtypes: float64(2), int64(8)
memory usage: 687.5 KB


In [50]:
x_test.shape

(2000, 10)

In [51]:
y_test.shape

(2000, 1)

In [52]:
df.Geography.unique()

array([0, 2, 1])

In [53]:
x.shape

(10000, 10)

In [54]:
y.shape

(10000, 1)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  int64  
 2   Gender           10000 non-null  int64  
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9)
memory usage: 859.5 KB


In [56]:
df['Exited'].unique()

array([1, 0])

In [57]:
type(x_test)

pandas.core.frame.DataFrame

In [71]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [59]:
df.head()

CreditScore  Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619          0       0  ...               1        101348.88       1
1          608          2       0  ...               1        112542.58       0
2          502          0       0  ...               0        113931.57       1
3          699          0       0  ...               0         93826.63       0
4          850          2       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [60]:
#df['Geography'] = df.Geography.astype(float)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  int64  
 2   Gender           10000 non-null  int64  
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9)
memory usage: 859.5 KB


In [72]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
model= LogisticRegression()
print(model.fit(x_train,y_train))
y_pred=model.predict(x_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
plt.show()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)


<IPython.core.display.Javascript object>

Accuracy:  0.815


<IPython.core.display.Javascript object>

In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [73]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print('accuracy score :' ,accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.97      0.89      1607
           1       0.60      0.18      0.28       393

    accuracy                           0.81      2000
   macro avg       0.71      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000

[[1559   48]
 [ 322   71]]
accuracy score : 0.815


In [74]:
from sklearn.ensemble import RandomForestClassifier as rfc
rfc_object = rfc(n_estimators=100,max_depth= 5, random_state = 1)
rfc_object.fit(x_train, y_train)
predicted_labels = rfc_object.predict(x_test)

In [75]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(classification_report(y_test, predicted_labels))
print(confusion_matrix(y_test, predicted_labels))
print(accuracy_score(y_test,predicted_labels))

              precision    recall  f1-score   support

           0       0.86      0.98      0.92      1607
           1       0.83      0.35      0.49       393

    accuracy                           0.86      2000
   macro avg       0.84      0.67      0.70      2000
weighted avg       0.85      0.86      0.83      2000

[[1578   29]
 [ 256  137]]
0.8575


In [76]:
print(rfc_object.score(x_test,y_test)*100)
print(rfc_object.score(x_train,y_train)*100)
#print(accuracy_score(y_test,predicted_labels))

85.75
85.91250000000001


In [77]:
'''import pickle
pickle.dump(model, open('model.pkl','wb'))'''

"import pickle\npickle.dump(model, open('model.pkl','wb'))"

In [78]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error,accuracy_score
data_dmatrix = xgb.DMatrix(data=x,label=y)
xg_reg = xgb.XGBRegressor(objective ='reg:linear', n_estimators = 100)
xg_reg.fit(x_train,y_train)
preds = xg_reg.predict(x_test)
predictions = [round(value) for value in preds ]
rmse = np.sqrt(mean_squared_error(y_test, predictions))
print("RMSE: %f" % (rmse))
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

[06:19:16] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


<IPython.core.display.Javascript object>

RMSE: 0.364692
Accuracy: 86.70%


In [94]:
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.metrics import mean_squared_error,accuracy_score
#data_dmatrix = xgb.DMatrix(data=x,label=y)
xg_cla = XGBClassifier(max_depth =5, n_estimators = 100)
xg_cla.fit(x_train,y_train)
preds1 = xg_cla.predict(x_test)
predictions1 = [round(value) for value in preds1]
rmse = np.sqrt(mean_squared_error(y_test, predictions1))
print("RMSE: %f" % (rmse))
accuracy = accuracy_score(y_test, predictions1)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

<IPython.core.display.Javascript object>

RMSE: 0.365377
Accuracy: 86.65%


In [95]:
import pickle
pickle.dump(model, open('model.pkl','wb'))